version: '3.4'

services:
  sut:
    build: ./test
    volumes:
      - ./test:/tests-dir
    depends_on:
      - neural-net-env
    links:
      - neural-net-env
    command: bash /tests-dir/run-test.sh

  neural-net-env:
    build: .
